routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'games', 'as' => 'games.',], function () {
    Route::get ('',       ['as' => 'index',  'uses' => 'GameController@index',]);
    Route::get ('create', ['as' => 'create', 'uses' => 'GameController@create',]);
    Route::post('store',  ['as' => 'store',  'uses' => 'GameController@store']);
    
    Route::group(['prefix' => '{id}',], function () {
        Route::delete('',         ['as' => 'destroy', 'uses' => 'GameController@destroy']);
//        Route::get   ('',         ['as' => 'update',  'uses' => 'GameController@update']);
//        Route::get   ('/details', ['as' => 'details', 'uses' => 'GameController@details']);
    });
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/SocialStream.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SocialStream extends Model
{
    
    protected $guarded = [];
    
}

app/SocialStreamGame.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SocialStreamGame extends Model
{
    
    protected $guarded = [];
    
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'api_token',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'api_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/API/SocialStreamController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\API\SocialStreamRequest;
use App\Repository\SocialStreamRepositoryInterface;
use App\SocialStream;
use Illuminate\Http\Request;

class SocialStreamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(SocialStreamRepositoryInterface $repository, SocialStreamRequest $request)
    {
        // todo: add pagination
        $data = $repository->findWith($request->get('filter', []))->map(function ($item) {
            return [
                'stream_id'    => $item->stream_id,
                'game_id'      => $item->game_id,
                'viewer_count' => $item->viewer_count,
                'date'         => $item->created_at,
            ];
        });
        
        return response()->json(['data' => $data]);
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return response(null, 501);
    }
    
    /**
     * Display the specified resource.
     *
     * @param  \App\SocialStream $socialStream
     *
     * @return \Illuminate\Http\Response
     */
    public function show(SocialStream $socialStream)
    {
        return response(null, 501);
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\SocialStream        $socialStream
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, SocialStream $socialStream)
    {
        return response(null, 501);
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\SocialStream $socialStream
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(SocialStream $socialStream)
    {
        return response(null, 501);
    }
    
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Rules\SocialStreamUniqueRule;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

use App\Rules\SocialStreamServiceExist;
use App\SocialStreamGame;

class GameController extends Controller
{
    
    public function index(SocialStreamGame $model)
    {
        return view('games.index', [
            'records'  => $model->all(),
        ]);
    }
    
    public function create()
    {
        return view('games.create', [
            'services' => app('socialStreamService')::avail(),
        ]);
    }
    
    public function store(Request $request, SocialStreamGame $model)
    {
        // custom validate
        $validator = Validator::make($request->all(), [
            'form.game_id'    => ['required_without:form.game_name'],
            'form.game_name'  => ['required_without:form.game_id',],
            'form.service'    => [
                'required',
                new SocialStreamServiceExist(),
                new SocialStreamUniqueRule($request->form['game_id'], $request->form['game_name']),
            ],
        ]);
    
        if ($validator->fails()) {
            return redirect(route('games.create'))
                ->withErrors($validator)
                ->withInput();
        }
    
        // search game
        /** @var \App\Contracts\SocialStream $service */
        $service = app('socialStreamService/' . $request->form['service']);
        
        $game = $request->form['game_id']
            ? $service->searchGameById($request->form['game_id'])
            : $service->searchGameByName($request->form['game_name']);
        
        if (!$game) {
            return redirect(route('games.create'))
                ->withErrors([
                    'Searching game not found',
                ])
                ->withInput();
        }
        
        // store data
        $model->create([
            'service'   => $request->form['service'],
            'game_id'   => $game->id,
            'game_name' => $game->name,
        ]);
        
        return redirect(route('games.index'));
    }
    
    public function destroy($id)
    {
        SocialStreamGame::destroy($id);
        
        return redirect(route('games.index'));
    }
    
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/games/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="top-left">
        <h1>Добавить игру</h1>
    </div>

    <div class="top-right">
        <a class="btn btn-abort" href="{{ route('games.index') }}">отмена</a>
    </div>


    <form id="games-add-form" action="{{ route('games.store') }}" method="POST">
        @csrf

        <div class="control-group">
            <div class="control-label">
                <label for="form[service]">Сервис</label>
            </div>
            <div class="control-input">
                <select class="control-select" name="form[service]">
                    <option value>Выберите сервис</option>

                    @foreach ($services as $service)
                        <option value="{{$service}}" @if ($service == old('form.service')) selected @endif >{{@ucfirst($service)}}</option>
                    @endforeach

                </select>
            </div>
        </div>

        <p>Укажите название или ID игры:</p>

        <div class="control-group">
            <div class="control-input">
                <input class="control-input" name="form[game_name]" type="text" value="{{ old('form.game_name') }}" placeholder="Название игры"/>
            </div>
        </div>


        <div class="control-group">
            <div class="control-input">
                <input class="control-select" name="form[game_id]" type="text" value="{{ old('form.game_id') }}" placeholder="ID игры"/>
            </div>
        </div>

        <div class="control-group">
            <button class="btn btn-success" type="submit">Добавить</button>
        </div>

    </form>

    <!-- errors -->


    @foreach ($errors->all() as $error)
        <p class="error-message">{{$error}}</p>
    @endforeach



    <script>
        (() => {
            document.querySelector('#games-add-form').addEventListener('submit', e => {
                let
                    $this = e.target,
                    name = $this.querySelector('input[name="form[game][name]"]'),
                    id = $this.querySelector('input[name="form[game][id]"]'),
                    service = $this.querySelector('select[name="form[service]"]'),
                    errClass = 'error',
                    callback = i => i.classList.contains(errClass);

                // [name, id, service].forEach(i => i.value
                //     ? i.classList.remove(errClass)
                //     : i.classList.add(errClass));

                if (callback(service) || (callback(name) && callback(id))) {
                    e.preventDefault();
                }
            });
        })()
    </script>
{{--}}
    <script>
        (() => {
            let

                service   = document.querySelector('.control-group select[name="form[service]"]'),
                search    = document.querySelector('.control-group input[name="form[search]"]'),
                searchBtn = document.querySelector('.control-group button[data-action="search"]'),
                game      = document.querySelector('.control-group select[name="form[game_id]"]');


            searchBtn.addEventListener('click', function () {
                let body = encodeURIComponent([
                    ['service', service.value],
                    ['search', search.value],
                ].map(i => i.join('=')).join('&'));

                fetch(@json(route('games.search')), {
                    method: 'post',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': document.querySelector('input[name="_token"]').value
                    },
                    body: JSON.stringify({
                        service: service.value,
                        search: search.value,
                    })
                }).then(r => r.json()).then(i => console.log(i));
            });

            // disable inputs.
            // search.prop('disabled', true);
            // game.prop('disabled', true);

            // console.log(service, search, game);
            //
            // // search.disabled    = true;
            // // searchBtn.disabled = true;
            // // game.disabled      = true;
            // //
            // service.addEventListener('change', function () {
            //     search.disabled = !this.value;
            //
            //     console.log('service:', !this.value);
            // });
            //
            // search.addEventListener('keyup', function () {
            //     console.log('value:', this.value);
            //
            //
            // });
        })();

    </script>

    {{--}}
@endsection

resources/views/games/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="top-left">
        <h1>Управление играми</h1>
    </div>

    <div class="top-right">
        <a class="btn btn-success" href="{{ route('games.create') }}">Добавить</a>
    </div>

    <div>
        <table class="table" width="100%" cellpadding="0" cellspacing="0">
            <thead>
            <tr>
                <th>ID</th>
                <th>Сервис</th>
                <th>Название игры</th>
                <th>ID игры</th>
                <th>Управление</th>
            </tr>
            </thead>

            <tbody>
            @forelse($records as $record)
                <tr>
                    <th>{{$record->id}}</th>
                    <th>{{$record->service}}</th>
                    <th>{{$record->game_name}}</th>
                    <th>{{$record->game_id}}</th>

                    <th class="control-panel">
                        {{--<button>Статистика</button>--}}

                        <form action="{{route('games.destroy', $record)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button>Удалить</button>
                        </form>

                    </th>
                </tr>
            @empty
                <tr><td colspan="99" align="center">Список пуст</td></tr>
            @endforelse
            </tbody>

        </table>
    </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <style>

        * {
            box-sizing: border-box;
        }

        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        /*.top-left {*/
            /*position: absolute;*/
            /*left: 10px;*/
            /*top: 10px;*/
        /*}*/

        /*.top-right {*/
            /*position: absolute;*/
            /*right: 10px;*/
            /*top: 18px;*/
        /*}*/

        .content {
            /*text-align: center;*/
        }

        .title {
            font-size: 84px;
        }

        .links > a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 13px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }

        h1 {
            line-height: 1.5em;
            margin: 0;
        }

        table.table tr {
            border: 1px solid gray;
            border-collapse: collapse;
        }

        table.table td {
            border-top: 1px solid gray;
            padding: 5px;
        }

        table.table th {
            font-size: 1.2em;
            font-weight: bold;
        }

        .page { padding: 80px 25px 0; }

        .btn {
            display: inline-block;
            border: 1px solid black;
            border-radius: 8px;
            padding: 10px 15px;
            text-align: center;
            text-decoration: none;
            cursor: pointer;
        }

        .btn-success {
            background: seagreen;
            color: white;
        }

        .btn-abort {
            background: firebrick;
            color: white;
        }

        .control-group {
            margin-bottom: 5px;
        }

        .control-group div.control-label {
            display: inline-block;
            width: 250px;
            margin-right: 25px;
        }

        .control-group div.control-input {
            display: inline-block;
            min-width: 400px;
        }

        .control-group select {
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
            padding: 4px 12px;
            width: auto;
        }

        .control-group input {
            border: 1px solid gray;
            border-radius: 4px;
            padding: 4px;
        }

        .control-group input, .control-group select {
            height: 35px;
            min-width: 300px;
        }

        .control-group input.error, .control-group select.error {
            border-color: red;
        }

        p.error-message { color: red; }

        .table thead th {
            border-bottom: 1px solid gray;
        }

        .table .control-panel form { display: inline-block; }

        main { position: relative; }

    </style>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>